Registr
Daria-Valitskaya/kapusta-back-end pull request #2
Opened 2021-12-11 15:56 UTC by RostyslavDubinin

2021-12-11 16:42 UTC, Daria-Valitskaya requested changes

2021-12-11 16:42 UTC, Daria-Valitskaya commented on .env-example
> +DB_HOST=mongodb+srv://kapusta:kapusta@cluster0.jsr3i.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
этого не должно быть в файле, это считается секретными данными, эти данные добавляются в файл .env локально у себя на машине

2021-12-11 16:42 UTC, Daria-Valitskaya commented on controllers/auth/login.js
> +      status: "error",
все ошибки взять из библиотеки http-errors, с правильнымы кодами

2021-12-11 16:42 UTC, Daria-Valitskaya commented on controllers/auth/login.js
> +
тут должна быть еще одна проверка на верификацию юзера

2021-12-11 16:42 UTC, Daria-Valitskaya commented on .env-example
> +SECRET='kapusta'
SECRET_KEY обзови пожалуйста

2021-12-11 16:42 UTC, Daria-Valitskaya commented on models/schemas/user.js
> +  },
нужно еще имя пользователя, что бы регистрацию он прошел

2021-12-11 16:42 UTC, Daria-Valitskaya commented on models/schemas/user.js
> +  email: Joi.string().required().email({
имя сюда

2021-12-11 16:42 UTC, Daria-Valitskaya commented on middlewares/validation.js
> +        return res.status(400).json({
используем библиотеку http-errors

2021-12-11 16:42 UTC, Daria-Valitskaya commented on controllers/auth/verifyEmail.js
> +    return res.status(404).json({
библиотеку подкл

2021-12-11 16:42 UTC, Daria-Valitskaya commented on controllers/auth/signup.js
> +  const user = await service.getOne({ email });
тут должен быть findOne метод

2021-12-11 16:42 UTC, Daria-Valitskaya commented on controllers/auth/signup.js
> +    return res.status(409).json({
библиотеку ошибок сюда и выкидываем ошибку через trow

2021-12-11 16:42 UTC, Daria-Valitskaya commented on controllers/auth/signup.js
> +    console.log("Email sent");
тут должен прийти ответ что успешная отправлено письмо

2021-12-11 16:42 UTC, Daria-Valitskaya commented on controllers/auth/logout.js
> +    code: 200,
это 204 ответ
res.status(204).json()

2021-12-11 16:42 UTC, Daria-Valitskaya commented on controllers/auth/logout.js
> +  await service.update(id, { token: null });
findByIdAndUpdate этот метод используем

2021-12-11 16:42 UTC, Daria-Valitskaya commented on controllers/auth/login.js
> +  await service.update(user._id, { token });
findByIdAndUpdate

2021-12-11 16:42 UTC, Daria-Valitskaya commented on app.js
> +app.use(express.static('public'));
где эта папка у тебя находится? если у тебя нигде не прописан аватар и самой папки нет

2021-12-11 16:42 UTC, Daria-Valitskaya commented on controllers/auth/login.js
> +  const user = await service.getOne({ email });
findOne

2021-12-11 16:42 UTC, Daria-Valitskaya commented on services/index.js
> +const users = require("./users");
откуда это взялось вообще?
и для чего нам папка сервисы?

2021-12-11 16:42 UTC, Daria-Valitskaya commented on services/users.js
> +const { User } = require("../models");
вся эта папка и все вот эти функции должны быть удалены и сделаны функции так как мы по структуре делали в наших дз, так будет понятнее всем

2021-12-11 16:42 UTC, Daria-Valitskaya commented on models/schemas/user.js
> +
нужно добавить аватар еще, и при регистрации ее добавить с помощь граватара

2021-12-11 16:45 UTC, RostyslavDubinin commented on .env-example
> +DB_HOST=mongodb+srv://kapusta:kapusta@cluster0.jsr3i.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
оно там и лежит, это я оставил для тех кто будет еще писать

2021-12-11 17:04 UTC, ChernykhGO requested changes

2021-12-11 17:04 UTC, ChernykhGO commented on controllers/auth/login.js
> +const { users: service } = require("../../services");
ну пойму зачем тут переименование

2021-12-11 17:04 UTC, ChernykhGO commented on controllers/auth/login.js
> +
if (!user.verify) {
    throw new BadRequest("User is not verified");
  }

2021-12-12 07:36 UTC, Daria-Valitskaya approved these changes

2021-12-12 07:36 UTC, merged